Add .config/erebusbat/notify.conf.sh Change attributes of bin/notify

diff --git a/bin/executable_notify b/bin/executable_notify
--- a/bin/executable_notify
+++ b/bin/executable_notify
@@ -2,6 +2,10 @@
 # set -x
 
 function notify_pushover() {
+  if [[ -z "$PUSHOVER_TOKEN" ]] || [[ -z "$PUSHOVER_USER" ]] || [[ -z "$PUSHOVER_SOUND" ]]; then
+    echo "***ERROR: PUSHOVER_TOKEN, PUSHOVER_USER or PUSHOVER_SOUND not set!"
+    exit 1
+  fi
   curl -s \
     -F "token=${PUSHOVER_TOKEN}" \
     -F "user=${PUSHOVER_USER}" \
@@ -11,42 +15,60 @@ function notify_pushover() {
 }
 
 function notify_telegram() {
+  if [[ -z "$TELEGRAM_TOKEN" ]] || [[ -z "$TELEGRAM_CHAT" ]]; then
+    echo "***ERROR: TELEGRAM_TOKEN or TELEGRAM_CHAT not set!"
+    exit 1
+  fi
   curl -s \
     --data "text=$MSG" \
     --data "chat_id=$TELEGRAM_CHAT" \
     "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" > /dev/null
 }
 
+function notify_cmux() {
+  if [[ -z $CMUX_WORKSPACE_ID ]]; then
+    echo "***ERROR: unknown cmux state!"
+    exit 1
+  fi
+  cmux notify --title "$MSG" --body "$1" &>/dev/null
+}
+
 MSG=$1
 SHOULD_SAY=$2
-PUSHOVER_TOKEN={{- (gopassRaw "erebusbat/pushover" | mustFromJson).token }}
-PUSHOVER_USER={{- (gopassRaw "erebusbat/pushover" | mustFromJson).user }}
-PUSHOVER_SOUND=bugle
-TELEGRAM_TOKEN={{- (gopassRaw "erebusbat/batsignal_bot" | mustFromJson).token }}
-TELEGRAM_CHAT=-1001748048923
 
 if [[ -z $MSG ]]; then
   MSG="Task Done"
 fi
 
+# Load config file
+NOTIFY_CFG=~/.config/erebusbat/notify.conf.sh
+if [[ -s $NOTIFY_CFG ]]; then
+  source $NOTIFY_CFG
+fi
+PUSHOVER_SOUND=${PUSHOVER_SOUND:-bugle}
+
 # Set these to `0` and they will auto turn on/off based on if the environment variables are set correctly
 # Set them to `-1` to disable them
-SEND_PUSHOVER=-1
-SEND_TELEGRAM=0
+# These should be set in $NOTIFY_CFG
+SEND_PUSHOVER=${SEND_PUSHOVER:-0}
+SEND_TELEGRAM=${SEND_TELEGRAM:-0}
+SEND_CMUX=${SEND_CMUX:-0}
 
 # Figure out which notification options we should be using
 if [[ $SEND_PUSHOVER -eq 0 && -n $PUSHOVER_USER && -n $PUSHOVER_TOKEN ]]; then SEND_PUSHOVER=1; fi
 if [[ $SEND_TELEGRAM -eq 0 && -n $TELEGRAM_CHAT && -n $TELEGRAM_TOKEN ]]; then SEND_TELEGRAM=1; fi
+if [[ $SEND_CMUX -eq 0 ]]; then command -v cmux &>/dev/null && SEND_CMUX=1; fi
 
 # Send messages that are enabled
+if [[ $SEND_CMUX -gt 0 ]]; then
+  notify_cmux
+fi
 if [[ $SEND_PUSHOVER -gt 0 ]]; then
   notify_pushover
 fi
 if [[ $SEND_TELEGRAM -gt 0 ]]; then
   notify_telegram
 fi
-
-
 if [[ -n $SHOULD_SAY ]]; then
   say "$MSG"
 fi
