Update bin_ensure.sh

diff --git a/run_onchange_bin_ensure.sh.tmpl b/run_onchange_bin_ensure.sh.tmpl
--- a/run_onchange_bin_ensure.sh.tmpl
+++ b/run_onchange_bin_ensure.sh.tmpl
@@ -1,5 +1,9 @@
 #!/bin/bash
-{{- $filePath := joinPath .chezmoi.homeDir "/.config/bin/config.json" -}}
-# {{ include $filePath | sha256sum }} ~/.config/bin/config.json
+if [[ ! -x ~/bin/bin ]]; then
+        echo "Could not find 'bin' binary"
+        exit 1
+fi
+{{ $filePath := joinPath .chezmoi.homeDir "/.config/bin/config.json" }}
+# Config HASH: {{ include $filePath | sha256sum }} ~/.config/bin/config.json
 cd ~
-bin ensure
+~/bin/bin ensure
